# Generated by Django 3.2.5 on 2021-07-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('authorizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizations',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
    ]
