# Generated by Django 3.2.5 on 2021-07-19 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0002_alter_authorizations_issuer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizations',
            options={'verbose_name_plural': 'authorizations'},
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='start_validity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
