# Generated by Django 3.2.5 on 2021-07-19 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0003_auto_20210719_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizations',
            name='start_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 15, 33, 13, 278838, tzinfo=utc)),
        ),
    ]
