# Generated by Django 3.2.5 on 2021-07-19 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0004_alter_authorizations_start_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizations',
            name='start_validity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 19, 15, 38, 54, 344932, tzinfo=utc)),
        ),
    ]
